using System;
using System.Diagnostics;
using System.IO;
using System.Text;
using CST.Conversion;
using Xunit;
using Xunit.Abstractions;

namespace CST.Avalonia.Tests.Performance;

/// <summary>
/// Baseline timings for the script converters (#86). Converts a real large book (DN1, ~442K Deva chars)
/// through each hot Deva-&gt;script converter and reports throughput. Run before/after the single-pass
/// optimization to measure the win. Not an assertion test — it always "passes" and just records timings.
/// </summary>
public class ScriptConverterPerformanceTests
{
    private readonly ITestOutputHelper _out;
    public ScriptConverterPerformanceTests(ITestOutputHelper o) => _out = o;

    private static string XmlDir =>
        Environment.GetEnvironmentVariable("CST_XML_DIR")
        ?? Path.Combine(Environment.GetEnvironmentVariable("HOME") ?? "/Users/fsnow",
                        "Library/Application Support/CSTReader/xml");

    [Fact]
    public void Baseline_ConvertDN1_PerScript()
    {
        var path = Path.Combine(XmlDir, "s0101m.mul.xml"); // DN1 mula
        if (!File.Exists(path))
            return; // DN1 absent (CI / fresh checkout): benchmark no-ops instead of failing

        // UTF-16-LE corpus; File.ReadAllText honors the BOM.
        var deva = File.ReadAllText(path);
        int chars = deva.Length;

        var converters = new (string Name, Func<string, string> Fn)[]
        {
            ("Deva2Ipe-ref", Deva2Ipe.ConvertReference), // frozen readable oracle (baseline)
            ("Deva2Ipe",  Deva2Ipe.Convert),             // optimized single-pass (#86)
            ("Deva2Latn-ref", Deva2Latn.ConvertReference),
            ("Deva2Latn", Deva2Latn.Convert),
            ("Deva2Cyrl-ref", Deva2Cyrl.ConvertReference),
            ("Deva2Cyrl", Deva2Cyrl.Convert),
            ("Deva2Mymr-ref", Deva2Mymr.ConvertReference),
            ("Deva2Mymr", Deva2Mymr.Convert),
            ("Deva2Beng-ref", Deva2Beng.ConvertReference),
            ("Deva2Beng", Deva2Beng.Convert),
            ("Deva2Guru-ref", Deva2Guru.ConvertReference),
            ("Deva2Guru", Deva2Guru.Convert),
            ("Deva2Knda-ref", Deva2Knda.ConvertReference),
            ("Deva2Knda", Deva2Knda.Convert),
            ("Deva2Gujr-ref", Deva2Gujr.ConvertReference),
            ("Deva2Gujr", Deva2Gujr.Convert),
            ("Deva2Telu-ref", Deva2Telu.ConvertReference),
            ("Deva2Telu", Deva2Telu.Convert),
            ("Deva2Khmr-ref", Deva2Khmr.ConvertReference),
            ("Deva2Khmr", Deva2Khmr.Convert),
            ("Deva2Mlym-ref", Deva2Mlym.ConvertReference),
            ("Deva2Mlym", Deva2Mlym.Convert),
            ("Deva2Sinh-ref", Deva2Sinh.ConvertReference),
            ("Deva2Sinh", Deva2Sinh.Convert),
            ("Deva2Thai-ref", Deva2Thai.ConvertReference),
            ("Deva2Thai", Deva2Thai.Convert),
            ("Deva2Tibt-ref", Deva2Tibt.ConvertReference),
            ("Deva2Tibt", Deva2Tibt.Convert),
        };

        const int iterations = 10;
        var results = new StringBuilder();
        results.AppendLine($"# Script converter baseline — DN1 ({chars:N0} chars), {iterations} iters, avg");
        results.AppendLine($"{"converter",-12} {"avg ms",8} {"MB/s",8}");

        foreach (var (name, fn) in converters)
        {
            var outLen = fn(deva).Length; // warm up + JIT
            var sw = Stopwatch.StartNew();
            for (int i = 0; i < iterations; i++) fn(deva);
            sw.Stop();
            double avgMs = sw.Elapsed.TotalMilliseconds / iterations;
            double mbPerSec = (chars * 2.0 / 1_000_000.0) / (avgMs / 1000.0); // chars*2 ~ UTF-16 bytes
            results.AppendLine($"{name,-12} {avgMs,8:F1} {mbPerSec,8:F1}   (out {outLen:N0})");
        }

        var report = results.ToString();
        _out.WriteLine(report);
        var outFile = Path.Combine(Path.GetTempPath(), "cst-converter-baseline.txt");
        File.WriteAllText(outFile, report);
        _out.WriteLine($"(written to {outFile})");
    }

    // Timings for the X->Deva reverse converters and the Ipe/Latn family (#86). Each is fed realistic input
    // generated by running the corresponding forward converter over DN1, then timed reference vs optimized.
    [Fact]
    public void Baseline_ReverseAndIpeLatn()
    {
        var path = Path.Combine(XmlDir, "s0101m.mul.xml"); // DN1 mula
        if (!File.Exists(path))
            return; // DN1 absent (CI / fresh checkout): benchmark no-ops instead of failing
        var deva = File.ReadAllText(path);

        // (name, input, reference fn, optimized fn)
        var cases = new (string Name, string Input, Func<string, string> Ref, Func<string, string> Fast)[]
        {
            ("Beng2Deva", Deva2Beng.Convert(deva), Beng2Deva.ConvertReference, Beng2Deva.Convert),
            ("Guru2Deva", Deva2Guru.Convert(deva), Guru2Deva.ConvertReference, Guru2Deva.Convert),
            ("Knda2Deva", Deva2Knda.Convert(deva), Knda2Deva.ConvertReference, Knda2Deva.Convert),
            ("Gujr2Deva", Deva2Gujr.Convert(deva), Gujr2Deva.ConvertReference, Gujr2Deva.Convert),
            ("Telu2Deva", Deva2Telu.Convert(deva), Telu2Deva.ConvertReference, Telu2Deva.Convert),
            ("Sinh2Deva", Deva2Sinh.Convert(deva), Sinh2Deva.ConvertReference, Sinh2Deva.Convert),
            ("Mlym2Deva", Deva2Mlym.Convert(deva), Mlym2Deva.ConvertReference, Mlym2Deva.Convert),
            ("Mymr2Deva", Deva2Mymr.Convert(deva), Mymr2Deva.ConvertReference, Mymr2Deva.Convert),
            ("Khmr2Deva", Deva2Khmr.Convert(deva), Khmr2Deva.ConvertReference, Khmr2Deva.Convert),
            ("Cyrl2Deva", Deva2Cyrl.Convert(deva), Cyrl2Deva.ConvertReference, Cyrl2Deva.Convert),
            ("Thai2Deva", Deva2Thai.Convert(deva), Thai2Deva.ConvertReference, Thai2Deva.Convert),
            ("Tibt2Deva", Deva2Tibt.Convert(deva), Tibt2Deva.ConvertReference, Tibt2Deva.Convert),
            ("Ipe2Latn",  Deva2Ipe.Convert(deva),  CST.Ipe2Latn.ConvertReference, CST.Ipe2Latn.Convert),
            ("Latn2Ipe",  Deva2Latn.Convert(deva), Latn2Ipe.ConvertReference, Latn2Ipe.Convert),
            ("Ipe2Deva",  Deva2Ipe.Convert(deva),  Ipe2Deva.ConvertReference, Ipe2Deva.Convert),
            ("Latn2Deva", Deva2Latn.Convert(deva), Latn2Deva.ConvertReference, Latn2Deva.Convert),
        };

        const int iterations = 10;
        var results = new StringBuilder();
        results.AppendLine($"# Reverse + Ipe/Latn converters — DN1-derived input, {iterations} iters, avg");
        results.AppendLine($"{"converter",-14} {"ref ms",8} {"fast ms",8} {"speedup",8}");

        foreach (var (name, input, refFn, fastFn) in cases)
        {
            refFn(input); fastFn(input); // warm up + JIT
            var sw = Stopwatch.StartNew();
            for (int i = 0; i < iterations; i++) refFn(input);
            sw.Stop();
            double refMs = sw.Elapsed.TotalMilliseconds / iterations;
            sw = Stopwatch.StartNew();
            for (int i = 0; i < iterations; i++) fastFn(input);
            sw.Stop();
            double fastMs = sw.Elapsed.TotalMilliseconds / iterations;
            results.AppendLine($"{name,-14} {refMs,8:F1} {fastMs,8:F1} {refMs / fastMs,7:F1}x");
        }

        var report = results.ToString();
        _out.WriteLine(report);
        var outFile = Path.Combine(Path.GetTempPath(), "cst-converter-reverse.txt");
        File.WriteAllText(outFile, report);
        _out.WriteLine($"(written to {outFile})");
    }
}
