using System;
using System.IO;
using System.Linq;
using CST.Conversion;
using Xunit;
using Xunit.Abstractions;

namespace CST.Avalonia.Tests.Conversion;

/// <summary>
/// Oracle tests for #86: each optimized converter's <c>Convert</c> must be byte-identical to its frozen
/// readable <c>ConvertReference</c> across the real corpus (all 217 Devanagari books). Reads book text
/// from disk, so no Devanagari glyphs appear in this source file. Add a [Fact] per converter as the
/// optimization rolls out.
/// </summary>
public class ConverterEquivalenceTests
{
    private readonly ITestOutputHelper _out;
    public ConverterEquivalenceTests(ITestOutputHelper o) => _out = o;

    private static string XmlDir =>
        Environment.GetEnvironmentVariable("CST_XML_DIR")
        ?? Path.Combine(Environment.GetEnvironmentVariable("HOME") ?? "/Users/fsnow",
                        "Library/Application Support/CSTReader/xml");

    [Fact]
    public void Deva2Ipe_FastMatchesReference()
        => AssertEquivalentOverCorpus("Deva2Ipe", Deva2Ipe.Convert, Deva2Ipe.ConvertReference);

    [Fact]
    public void Deva2Latn_FastMatchesReference()
        => AssertEquivalentOverCorpus("Deva2Latn", Deva2Latn.Convert, Deva2Latn.ConvertReference);

    [Fact]
    public void Deva2Cyrl_FastMatchesReference()
        => AssertEquivalentOverCorpus("Deva2Cyrl", Deva2Cyrl.Convert, Deva2Cyrl.ConvertReference);

    [Fact]
    public void Deva2Mymr_FastMatchesReference()
        => AssertEquivalentOverCorpus("Deva2Mymr", Deva2Mymr.Convert, Deva2Mymr.ConvertReference);

    [Fact]
    public void Deva2Beng_FastMatchesReference()
        => AssertEquivalentOverCorpus("Deva2Beng", Deva2Beng.Convert, Deva2Beng.ConvertReference);

    [Fact]
    public void Deva2Guru_FastMatchesReference()
        => AssertEquivalentOverCorpus("Deva2Guru", Deva2Guru.Convert, Deva2Guru.ConvertReference);

    [Fact]
    public void Deva2Knda_FastMatchesReference()
        => AssertEquivalentOverCorpus("Deva2Knda", Deva2Knda.Convert, Deva2Knda.ConvertReference);

    [Fact]
    public void Deva2Gujr_FastMatchesReference()
        => AssertEquivalentOverCorpus("Deva2Gujr", Deva2Gujr.Convert, Deva2Gujr.ConvertReference);

    [Fact]
    public void Deva2Telu_FastMatchesReference()
        => AssertEquivalentOverCorpus("Deva2Telu", Deva2Telu.Convert, Deva2Telu.ConvertReference);

    [Fact]
    public void Deva2Khmr_FastMatchesReference()
        => AssertEquivalentOverCorpus("Deva2Khmr", Deva2Khmr.Convert, Deva2Khmr.ConvertReference);

    [Fact]
    public void Deva2Mlym_FastMatchesReference()
        => AssertEquivalentOverCorpus("Deva2Mlym", Deva2Mlym.Convert, Deva2Mlym.ConvertReference);

    [Fact]
    public void Deva2Sinh_FastMatchesReference()
        => AssertEquivalentOverCorpus("Deva2Sinh", Deva2Sinh.Convert, Deva2Sinh.ConvertReference);

    [Fact]
    public void Deva2Thai_FastMatchesReference()
        => AssertEquivalentOverCorpus("Deva2Thai", Deva2Thai.Convert, Deva2Thai.ConvertReference);

    [Fact]
    public void Deva2Tibt_FastMatchesReference()
        => AssertEquivalentOverCorpus("Deva2Tibt", Deva2Tibt.Convert, Deva2Tibt.ConvertReference);

    // X->Deva reverse converters: input is generated by running the corresponding Deva2X over the corpus.

    [Fact]
    public void Telu2Deva_FastMatchesReference()
        => AssertEquivalentOverCorpus("Telu2Deva", Telu2Deva.Convert, Telu2Deva.ConvertReference, Deva2Telu.Convert);

    [Fact]
    public void Gujr2Deva_FastMatchesReference()
        => AssertEquivalentOverCorpus("Gujr2Deva", Gujr2Deva.Convert, Gujr2Deva.ConvertReference, Deva2Gujr.Convert);

    [Fact]
    public void Knda2Deva_FastMatchesReference()
        => AssertEquivalentOverCorpus("Knda2Deva", Knda2Deva.Convert, Knda2Deva.ConvertReference, Deva2Knda.Convert);

    [Fact]
    public void Guru2Deva_FastMatchesReference()
        => AssertEquivalentOverCorpus("Guru2Deva", Guru2Deva.Convert, Guru2Deva.ConvertReference, Deva2Guru.Convert);

    [Fact]
    public void Sinh2Deva_FastMatchesReference()
        => AssertEquivalentOverCorpus("Sinh2Deva", Sinh2Deva.Convert, Sinh2Deva.ConvertReference, Deva2Sinh.Convert);

    [Fact]
    public void Mlym2Deva_FastMatchesReference()
        => AssertEquivalentOverCorpus("Mlym2Deva", Mlym2Deva.Convert, Mlym2Deva.ConvertReference, Deva2Mlym.Convert);

    [Fact]
    public void Beng2Deva_FastMatchesReference()
        => AssertEquivalentOverCorpus("Beng2Deva", Beng2Deva.Convert, Beng2Deva.ConvertReference, Deva2Beng.Convert);

    [Fact]
    public void Mymr2Deva_FastMatchesReference()
        => AssertEquivalentOverCorpus("Mymr2Deva", Mymr2Deva.Convert, Mymr2Deva.ConvertReference, Deva2Mymr.Convert);

    // Ipe/Latn family. IPE input is generated by Deva2Ipe; Latin input by Deva2Latn.

    [Fact]
    public void Ipe2Latn_FastMatchesReference()
        => AssertEquivalentOverCorpus("Ipe2Latn", CST.Ipe2Latn.Convert, CST.Ipe2Latn.ConvertReference, Deva2Ipe.Convert);

    [Fact]
    public void Latn2Ipe_FastMatchesReference()
        => AssertEquivalentOverCorpus("Latn2Ipe", Latn2Ipe.Convert, Latn2Ipe.ConvertReference, Deva2Latn.Convert);

    [Fact]
    public void Ipe2Deva_FastMatchesReference()
        => AssertEquivalentOverCorpus("Ipe2Deva", Ipe2Deva.Convert, Ipe2Deva.ConvertReference, Deva2Ipe.Convert);

    [Fact]
    public void Latn2Deva_FastMatchesReference()
        => AssertEquivalentOverCorpus("Latn2Deva", Latn2Deva.Convert, Latn2Deva.ConvertReference, Deva2Latn.Convert);

    // Claude-written stateful X->Deva converters (Substring/Dictionary loops, optimized to char tables).

    [Fact]
    public void Khmr2Deva_FastMatchesReference()
        => AssertEquivalentOverCorpus("Khmr2Deva", Khmr2Deva.Convert, Khmr2Deva.ConvertReference, Deva2Khmr.Convert);

    [Fact]
    public void Cyrl2Deva_FastMatchesReference()
        => AssertEquivalentOverCorpus("Cyrl2Deva", Cyrl2Deva.Convert, Cyrl2Deva.ConvertReference, Deva2Cyrl.Convert);

    [Fact]
    public void Thai2Deva_FastMatchesReference()
        => AssertEquivalentOverCorpus("Thai2Deva", Thai2Deva.Convert, Thai2Deva.ConvertReference, Deva2Thai.Convert);

    [Fact]
    public void Tibt2Deva_FastMatchesReference()
        => AssertEquivalentOverCorpus("Tibt2Deva", Tibt2Deva.Convert, Tibt2Deva.ConvertReference, Deva2Tibt.Convert);

    // For X->Deva (reverse) converters: the raw corpus is Devanagari, so generate realistic script-X input by
    // running the corresponding (already-verified) Deva2X converter over each book, then feed that to X2Deva.
    // Both Convert and ConvertReference get the same input, so the equivalence check is valid either way. (#86)
    private void AssertEquivalentOverCorpus(string name, Func<string, string> fast, Func<string, string> reference,
                                            Func<string, string>? prep = null)
    {
        var dir = XmlDir;
        if (!Directory.Exists(dir))
            return; // XML corpus absent (CI / fresh checkout): integration test no-ops instead of failing
        var files = Directory.GetFiles(dir, "*.xml").OrderBy(f => f, StringComparer.Ordinal).ToArray();
        if (files.Length == 0)
            return; // no book XML files: integration test no-ops

        int checked_ = 0;
        long chars = 0;
        foreach (var f in files)
        {
            var deva = File.ReadAllText(f); // UTF-16-LE corpus; BOM honored
            var input = prep != null ? prep(deva) : deva;
            var a = fast(input);
            var b = reference(input);
            if (!string.Equals(a, b, StringComparison.Ordinal))
            {
                int at = FirstDiff(a, b);
                Assert.Fail(
                    $"{name} mismatch in {Path.GetFileName(f)} at index {at} (lenFast={a.Length}, lenRef={b.Length})\n" +
                    $"  fast: [{Snippet(a, at)}]\n" +
                    $"  ref : [{Snippet(b, at)}]");
            }
            checked_++;
            chars += deva.Length;
        }
        _out.WriteLine($"{name}.Convert == ConvertReference across {checked_} books ({chars:N0} chars), byte-identical.");
    }

    private static int FirstDiff(string a, string b)
    {
        int m = Math.Min(a.Length, b.Length);
        for (int i = 0; i < m; i++)
            if (a[i] != b[i]) return i;
        return m;
    }

    private static string Snippet(string s, int at)
    {
        int start = Math.Max(0, at - 12);
        int len = Math.Min(24, s.Length - start);
        return len > 0 ? s.Substring(start, len) : "(end)";
    }
}
